### ISSUE TITLE
Usage Instructions

### ISSUE THREAD

**Issue by ireasor** [badvision/curly#1]
Might be nice to have usage instructions in the README :)

**Comment by badvision** [comment]
100% agreed.  First I have to get it to a usable enough working state -- check back on Monday.

**Comment by badvision** [comment]
Wiki pages are being added to address this issue.  Thank you for your interest!  https://github.com/badvision/curly/wiki/How-to-Start-Curly
https://github.com/badvision/curly/wiki/How-to-Use-Curly
